apiVersion: 1

datasources:
  - name: InfluxDB-FireSense
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: firesense
      defaultBucket: sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    editable: true
    isDefault: true
    uid: influxdb-firesense
