---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: harbor-credentials
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgC2eRItYeS3UgbuiJiu7yzDfTnphJkhT+/63LdqhaBfShbXurkd/1QY2h3ZFVIlva4UqTqPGm1mieaDMUJ41dIiaDj7TPK+Z9pqKmfWk9fn6cM36HB8FouOaKPS/RlaMA7BK01ubpd4CxzcW3RdD94PMZo7Hj7dX+H5jFShcpkIR4WMN/t2Bx+wfUduOnGXcyfjPV/Hf3L8/dKIGuC2IiG0iRoiY+w0VKPdTdR4XepkqHt1m3sEPOD6x+RO3GWK+czz4zTGVLxbVbiIzJh0Gs2LMu5rJopBQcQQlarEsATw1rqieH+PSg4tlG/fOZIPVWnBDOlRq+p3AMxYufQxfOz7/EXcikTVc0IcvrbaMFTn0wbJRllWivn455HA+OG0pJUCHIh9Feoy5DOQCaoccGuF+XuIkquXXvS7O5P0IsOPW/hrF9mwOyz6M/HVuG2/cfjx3TN1sdypnDb0LovP7Ld3B5p8OwuzB2KJH6858qTst5DSWHvDsOU7JBHj0oKlYYc6c5gQt72rzItJ2odkq3aWRFb6Jh0VyUx0tcSjAXsCsF+nj4IcJ/gAGGJ84Isg/kzDJSGpwfGJwYy+mz4DCKpLgmmghWvQJPQrtNrlO39uAq4x1j9p+9Dm8ooPxgA3pry95nYz1/IB1SLKc++UIG/8aCFSRWKEiH13gKVGXXUNi90hMx9cOn/mcbeYDBHu9N2tJ3IXERzCxUAejfIpcadPYEthemJsaKr5EmrEC+73xK5yPuh6pK9PYNIa9rAAlp9UBCBvRIHd8OY+Y2USZRHm/oet4l8eoSmMfE3JhfcG9R1OHyaeqOvjsp1m9re7Nq/GYXg+oUzPyDxsTfloaDcF0PfCGxRiqSVabMxUm2JL1+mK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: harbor-credentials
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
