---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: chirpstack-postgres-secret
  namespace: iot
spec:
  encryptedData:
    password: AgCIgJMoC/XIyfQphgjg9ildvWkqmcwyXJ5AxfNZNDlPkW4ugZo3Og0t8ov1/iv2xVqn17N4aqi6511v+DRK8pb2jfntOg1bjyaEqW+Huje5jHeo5R0SQ4XhhuUv/Py5VT3mPkW4rzM4vt+ZGCsEeX4uWAK0EEiIg/GnIKIRrn0LA5nIvrHLnh7N/Wyq4ObXKYn0tpDwyOh6fOKFBCPYW8M6oUwOY8ZPpV6dcwOzeWegIwK2hjMUnOjQr6gTJH+nfnsVkHlJfzVLGJIg/ynEMieNHFx0YwaXjszNlAoOQWPkZW3R8cxBam9kay7pqZsQztT+kWs2xjXvGVRN0NxxyS70E88Z+k8YqZMj0eIUIVwDe60ZscQLAG9hYW7r0h5o4v805sEDGmmEh/8fUs9mQvT/0Rn63xNXq1rR7GhSmrJJD2aTmWvKg4LKJ81ZtSqbYCNOppHzD6yjbRRjzRm1cVtSqOxU4N966yrvS7wU1kQDjckootULSiRg6AFZrWi/dPWIwO+QnYH5Wfc5hND0s9guwQbHymkLHHGP0ULFe6dIkkyKhSy7fr6HUju9fetp02i0dJoiFZiWU1ORcddr1ZMESyzdiS/ImZEZHiTIdmCaihfD46CS+R8rTScqy42c0f5YcUeDvhaCJYXYbKs7u6qJ3vABUcbDbvzQWcr6yfm/6YBWElWZxQ77NG7RItKz/qBD4NXp5adYhqRusTnc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: chirpstack-postgres-secret
      namespace: iot
    type: Opaque
