---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backup-ssh-key
  namespace: iot
spec:
  encryptedData:
    id_rsa: AgAXTdjle5d4BOQgSXkbiOYoNk4vmkkcsDouiR/AOcv6C6cwDVmrRLyzAAOFT/URWwFTy2CgRFvmtDd09QQkCuT/LOWy+lJiYxN3k1dgSNrw5q4wtbtk1vEBZrN4NBW1pZu0LjL0ISHhYkIw8HnnXXrDi2Qx+HoObYkGFIAWCCSI1ovMkPO6/SAA7l81xW7VAD7UgjznzR8u7RYCYs16wwZHVgRpQzbNNp4JG7CkBc6gNYVUDG67UoAUvoLWN7zHsb0XiP1Ir1m/IX83Ou8hWvsdHY8EeGXUdbiPo7kVf6xNDhIzkuLyfpNVVgNNohKvVCYzMShxwx6goGXAVV4bOpnn7xaf8UsRpmLi21/rdR0p4bEMqR9u8eFb0myIBvjmlfYou0ZnxByED/hFmKnRgMLKPK7IoSZa9tkpsU5IG+JtvmlN4L9YzELYgHU8NI0m3KDfdSw2+b08L16RyXtg2H7+e3siAHBgoY37nYoNABr6veTQib8Zj/+VhJfCVTO7me04h0enheJWjG+HaQTAoiJbkpYuelCsTFp2vS/e1ZJvRUsEPzvBQkmE9zwzHfz3+E6uAUJLaeJ+yZdjIqZNjRFaS/Oy66dQnbtwBDMfRxY+QQncezhhU4vyp4nUNkOJCO/d9W1iryJSdiKQCESyBvlv1Z/3ZGtNVUjeDTHQgQkoLCYBQ+Rp/a5YkxHnOd8hRGI1Q3xnZ45YwFBTHar5fpQ1eC7lewqczQC7ksdbnXBmCtqoEg5oZfniNUmahJmLuELWg2wHnvVDkXqDutyjisxd/meaOxHvsLJ6xMpTVWmVeDsl1ijQBpIrLiwb+iSdf6DyLt2lQsnBcu8H6W+CjE0eEbwkNjbzn7CRxxZ5sShF3iV5bErXAaNBzC1DJi3Ai/6wywI5hPHt4E2QtMGvBJhLPPMltViK6N0CQvUldMFJHr7FHBMydhBtiROSOmAdbVjjs/G+AtHyzdSQ6Pnhe7mTPPsUVbmc5q2BlUE2UuQyT2jKz2S8hjHdc2Drwb2F3VG6T8IQPe1JWJw5mERmkGEWc+hJvVudQo5E7OH/GzzIch274EpMYEyEj4qQouv0cAKV4bd0JwmJ7BE69B8ofnaOxsdicd7g29VIerL2mMfC5vcjA2cbUIso3bF2RwhrIwobf6IpbaUOZwtnTsx4rsOjcZW0IEF/sJJYCokx9VMnI+1g+sk4NcEpt7gD7wJrt5FFKKrHGFudJe4FX/V83JbCZypx4zTWLSaRPBY=
  template:
    metadata:
      name: backup-ssh-key
      namespace: iot
