---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: iot
spec:
  encryptedData:
    .dockerconfigjson: AgDGvqWzBsWHCQGrs2rqA+c++U/MYxpM/BUpq1aWTKJXAEDJoGYETiaSHjLYTXTM4XTSiYTPyTJ3rEE7vIaxsGznuhfqd7VrYgE9soeNKNA1f4XJytMaL+VysJERRr9UOfJShWyY00x0/uzNoEdQlWabrinouwQfgn4TZLK9xbXE0Rv6PulBrP1vLut//qAeFwAnKoLbCvbovkZohQEWpX0fKssWhZ+n9CessQk9ez1OOOqyOC7X4izpky3wZAyDV/33E1pgFz9fep2gesGr14NFWL7ycrnZ30LFhtKCG1gIGwSvDtQ48uzoSYg4Uf/fWw2auO+PPMSofFvXap/5H7zTma9rfWSHsgNnY3eN8vZTdqsBDwuR5lZAn37dmYR22WGJUKiDgGvAGl5VMTI+I56F4kJnb3iV/pGAUpeKhdwSuWnLolVtM8z0aLIVbtjrNBQ/BdccJpX8SOD3qVTvEyQDr3M/bKQxZDfoMzaBbDKYYlGPXXT95Lo74bnR6EXdCXx/XiQRFaH+iGhfDxWHoD6ZlZDO/Jq3P9YLRURpL22zTEB7LccFjN0mR5tyr7YnkL9jZS1QmfiQimdmqWQr4LK841W1hbkre0IsNROY467IJuDeBTWyTIYnI0zfpIW2LdLmt00y2NcV6TQRPv0NkvcR/4Qh5ipSrnnobZMhqu8UEzc9oEwBcGuRir3vshW9d8ogkLHeh7kcfqFoCieQfHC9XWS5xP8yZm1g6n6yte40F3FrhAfW3W7H0wh9uvz+RDR1lVF9Z68EzvzXPZJ34UsEEVhpvsNzO58nomrh8bv0zxZUMuAS5zQzB0Kt4h1AEb8kkwlU0Np93yyTePIBJjV63QaQlZM0Y5sLpn+sIaFbvWtaSRH8N+cs0qvWJmMyF1G8zVgtJVz6N2/pzhX9oRXTlg38kWcLG+5hGzdG2pIi5NHBYMgAyiUJr/M2z48=
  template:
    metadata:
      name: harbor-pull-secret
      namespace: iot
    type: kubernetes.io/dockerconfigjson
