---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: firesense
spec:
  encryptedData:
    .dockerconfigjson: AgCkXN41HPh/v51TcJWa6hFeRbrX/amU2Ppf6EgTpfFvdb+uljaQOw+CVdg0p1ToeI1O7VEFrZJ3HYloWlE3egoqQ0luquYOLR/i/TQLo/zIpDKBIZAtjAFN11p9oaq3Hs659JFuQ+T1VP+zTJymXmNKZytp3O4fA+15rup9hibwzM7NZYtJfGyJsuVo1uBQbfMBzwX0QOeycOIcvvRMDWuwls8OanIDiiklTqxsK2JjofnmB1m6ulwaepTYTlQBpkCLwFU2I9XJEokfXUoz1DnQezFTvzMDQraQ395kESsseleZDUGA7qkuGwjwUNP8CLA6dmRQ0AqqDaafN0PfoQUccZ6weDuiMhsaRFTtW88EmcIt1tDITvm5yjZL93445RBOTU953zF0FU3WM7H1po+KhuPPiI4hA98FROppvA/u48V2xkW4mfZDNH2Jl+RGZFqQbAYFF4nHu2MClsKQBQAEhwrTo/5c9lGX5WyVqmqd6e4uoMGiOBznoxKlkC3jZ1DH2IimUVjM2odfEZbHNQ2dWyZ4sp1+hIzQDwFMF0C4WsUqC4gdfRwrFiAcqMCngVPgY/G2AfFxA1zcE21LCa74iVL0FgOzhKP4mrE8b25sU9LXjHf3HLCKh7q3Cl6VIo33KA7KOj6aJAET8uNu/y+Zfz8cXI2+RXgjceojmjESADUdLA06SDzC+YLp3fYZ3kU2xFaNY+VGPNsfKDoC00mofJJT5oyue7QMA663b7LtwWuzHxTnKeMkYKR7euvAfJl8FfOGWq4o6s7O4ZmeF5mlb5eqZc8bC4KPjpDrukkuGMS39j/2uH/N711xnoIVddc/Iw791/L2Hqui2JW7PlYgkqXn/u6GvNG0HBnNwOiWs/n0RXAjHGaJmRApEuTXKU/aJ+4hp46zT5M+bL5vph3YcpVdQibLUWRDH73rkBORTuqOHDFDU0X7hydwWfI=
  template:
    metadata:
      name: harbor-pull-secret
      namespace: firesense
    type: kubernetes.io/dockerconfigjson
