---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chirpstack-postgres-secret
  namespace: iot
spec:
  encryptedData:
    password: AgAyFxoOLUOlCondwVIC3yqw7me6j205DW53MWn9gVHC0gEjclQxexS7XtIyUhC4o6MCzsNnOMA6eRCqOMs5K9TlYjkxDJ2yte+uUNYmfGaOu40GJLjZyFk8kRYTklwqm6Z3Y6j8xkC2OthAWScIaSLipLUY0U4uuHy4SCjPK7UItBX9aYpfxA0AtVqPPkZk6FHLGbaEcm6xk5BIDUCdqGh1wEHwx6DAzXvI1XW1ysE7ZnFlY9AxwfyHQynPzxsMNPwl5rSg1ppd7hi8+hYJMGwB/26OX6QWFMAkVIgFv5jbV83SI+8r3BJDSyRwir6giDzkspsO0X6StjHXMnXvGYxURjIAyXLJvvRghNmYCAchWwFdKH75587w01wE6F9iAxb8LM7TD8oPgz+OgjppsF1cpWU6bgdlZEzm73DQTjGrLna4GhzFSbGuh7iJU6VWT2ML+pJsUUSbrsn7eV0iFjipYK8DnxcCR0v2AZ6Zie8wEu//WJjc7htGLK2XORETmcMJyZyQSby4xpJavtJauUB5suAJZKmCVwYaiJ3GxKF+8iPcu5RwSvdkXTmkV1zPoLhzN8oOomtHMTbLyHr4bLPFpSZcSv7BEaETNlnP7klg9P9D1fcrezpSOso8VI6vWIcRWvtQqB+MxlFIVlnavrvCp8oe9YeoiNoElalS9i4PBIdemULeeF7w7So6QiH0QQCcJ7NXU2oWuh9vyqAj
  template:
    metadata:
      name: chirpstack-postgres-secret
      namespace: iot
    type: Opaque
