nodeSelector:
  kubernetes.io/hostname: k8s-worker01

deployment:
  kind: Deployment
  replicas: 1

ports:
  web:
    port: 8000
    exposedPort: 80
    hostPort: 80
    protocol: TCP
  websecure:
    port: 8443
    exposedPort: 443
    hostPort: 443
    protocol: TCP

service:
  type: ClusterIP

ingressRoute:
  dashboard:
    enabled: false

api:
  dashboard: true
  insecure: false

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true